[project]
name = "journal"
requires-python = ">=3.12"
version = "0.1.0"
description = "Journaling Web App using Django"
authors = [{ name = "Nabil Khalil", email = "nabilamirkhalil@gmail.com" }]
readme = "README.md"
dependencies = [
    "django>=6.1.1,<7",
    "django-bootstrap5>=26.3",
    "platformshconfig>=2.4.0,<3",
]

[dependency-groups]
dev = ["ruff>=0.16.10"]
deployment = [
    "gunicorn>=26.2.0",
    "psycopg2-binary>=2.9.13",
]

[tool.uv]
package = false
